spring:
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp
moviefun:
  datasources:
    movies:
      url: jdbc:mysql://localhost:3306/movies?useSSL=false
      username: root
      password: Nikita@123
    albums:
      url: jdbc:mysql://localhost:3306/albums?useSSL=false
      username: root
      password: Nikita@123